Juniper/contrail-windows-ci

monitoring/README.md
monitoring/grafana/build-statistics.yml
monitoring/grafana/grafyaml.conf.sample
monitoring/requirements.txt

- `grafyaml` does not support `table` as panel type as of yet

grafana: initial version of dashboards in YAML

---

CIScripts/GenerateTestReport.ps1
Jenkinsfile
ansible/roles/tester/tasks/main.yml

Blocked by: https://github.com/Juniper/contrail-windows-ci/pull/1

pester: generate report in HTML

---

ansible/group_vars/jenkins-slave/vars

@PawelMarchewkaCodiLime 
Last failed `deploy-builder`: http://10.84.12.26:8080/job/WinContrail-infra/job/deploy-builder/133/console

Use jenkins_agent_master from vault

---

CIScripts/Common/Invoke-CommandInLocation.Tests.ps1
CIScripts/Common/Invoke-NativeCommand.Tests.ps1
CIScripts/Common/Invoke-UntilSucceeds.Tests.ps1
CIScripts/Report/GenerateTestReport.Tests.ps1
CIScripts/Report/Repair-NUnitReport.Tests.ps1
CIScripts/Test/PesterHelpers/PesterHelpers.Tests.ps1
CIScripts/Test/PesterLogger/Get-CurrentPesterScope.Tests.ps1
CIScripts/Test/PesterLogger/PesterLogger.Tests.ps1
CIScripts/Test/Tests/Integration/DockerDriver.Tests.ps1
CIScripts/Test/Tests/Integration/VTestScenarios.Tests.ps1
CIScripts/Test/Tests/Integration/vRouterAgentMSIInstaller.Tests.ps1
CIScripts/Test/Tests/Integration/vRouterAgentService.Tests.ps1
CIScripts/Test/Tests/Protocol/SingleHostWithUtils.Tests.ps1
CIScripts/Test/Utils/DockerImageBuild.Tests.ps1
CIScripts/Testenv/Testenv.Tests.ps1
CIScripts/Testenv/Testenv.ps1
Invoke-Selfcheck.ps1
SELFCHECK.md

Implemented selfcheck in https://github.com/Juniper/contrail-windows-ci/pull/95
Had to revert it in https://github.com/Juniper/contrail-windows-ci/pull/98, because of concurrent merge.
Reopening with fix.

Implement CI selfcheck script (fixed).

---

CIScripts/Build/BuildFunctions.ps1
CIScripts/Checkout/Zuul.ps1
CIScripts/clonemap.yml
ansible/roles/zuul/files/layout.yaml
ansible/update-zuul-layout.py

Don't use deprecated contrail-generateds repo

---

CIScripts/Test/PesterLogger/PesterLogger.Tests.ps1
CIScripts/Test/PesterLogger/PesterLogger.ps1
CIScripts/Test/PesterLogger/RemoteLogCollector.Tests.ps1
CIScripts/Test/TestConfigurationUtils.ps1
CIScripts/Test/Utils/ComponentsInstallation.ps1
CIScripts/Test/Utils/DockerImageBuild.ps1

(with a fallback to Write-Host)

Import PesterLogger explicitely

---

Jenkinsfile
ansible/group_vars/jenkins-server/vars
vars/decideTestReportsUrl.groovy
vars/getLogsURL.groovy
vars/isGithub.groovy
vars/sendGithubComment.groovy

(please review also) PR describing how it was verified: https://github.com/Juniper/contrail-windows-docs/pull/4
link to check job: http://10.84.12.26:8080/job/WinContrail/job/winci-server2016-devel-gerrit-check/1/

Send GitHub comment with link to logs from Jenkinsfile.

---

ansible/roles/controller/templates/docker/daemon.json.j2

Contrail-kolla-ansible now handles insecure-registry

Sync with changes in contrail-kolla-ansible

---

Jenkinsfile
ansible/files/provision_vm.py
ansible/files/vmware_api.py
ansible/roles/vmware-vm/tasks/deploy.yml

Add linked clone

---

CIScripts/SpawnTestbed.ps1
CIScripts/Test/PesterLogger/PesterLogger.ps1
CIScripts/Test/Utils/RegisterDefaultResorces.ps1

Clean up the code so the [shelly](https://github.com/krdln/shelly) analyzer passes cleanly.

Clean up some imports and dead code

---

Jenkinsfile
vars/tryUnstash.groovy

This should help with "no logs on testenv provisioning error" issue.

Catch unstash errors and add tryUnstash

---

ansible/roles/zuul/files/layout.yaml

Added  branches       - ^release-3.7-contrail$    - ^release-3.9-contrail$ for openshift ansible

added branches for openshift ansible to check job

---

ansible/roles/zuul/files/layout.yaml

Branch contrail/queens is needed by the contrail-kolla-ansible repo

Add branch to the check pipeline trigger filter

---

CIScripts/Build/BuildFunctions.ps1

Merge after https://review.opencontrail.org/#/c/43914/ but before https://review.opencontrail.org/#/c/43912

Use ./Invoke-Build.ps1 to build docker driver.

---

flakes/README.md
flakes/patterns.txt
flakes/tests/certificates.in.txt
flakes/tests/certificates.out.txt
flakes/tests/dep-ensure.in.txt
flakes/tests/ps-remoting-access-denied.in.txt
flakes/tests/waiting-for-ethernet1.in.txt

Also, add descriptions of current flakes.

Add certificates related error to flakiness patterns

---

CIScripts/Report/Repair-NUnitReport.Tests.ps1
CIScripts/Report/Repair-NUnitReport.ps1
CIScripts/TestRunner/Invoke-PesterTests.ps1

See CISelfcheck pretty report dir to see how Index.html looks and that it is fixed: http://logs.opencontrail.org/winci/github/WinContrail/contrail-win-ci-gh/2000

Fix erroneous counters in reports dashboard.

---

utility/update_docker_registry/README.md
utility/update_docker_registry/update-docker-registry.py

Please see: https://github.com/Juniper/contrail-windows-docs/pull/29

Script for updating local docker registry

---

Jenkinsfile
Test/Tests/Protocol/SingleHostWithUtils.Tests.ps1
Test/Tests/Protocol/TunnellingWithAgent.Tests.ps1

Using template with changes from https://github.com/Juniper/contrail-windows-ci/pull/264

Enable fragmentation tests

---

CIScripts/Common/Invoke-UntilSucceeds.Tests.ps1
CIScripts/Common/Invoke-UntilSucceeds.ps1
Test/TestConfigurationUtils.ps1
Test/Utils/DockerImageBuild.ps1

And some refactors in `Invoke-UntilSucceeds` so it's usable in more places.

Retry docker build on "syscall timeout" failure

---

Test/Utils/CommonTestCode.ps1

_Perhaps_ we try to obtain the IP before it's set on the container. So let's add some logging and check if that hypothesis is true. I think that's impossible, but it's better to be sure.

Retry loop for getting container IP

---

flakes/patterns.txt
flakes/run-tests.sh
flakes/tests/unable-to-communicate-with-the-remote-host.in.txt
flakes/tests/unable-to-communicate-with-the-remote-host.out.txt

Spotted: http://logs.opencontrail.org/winci/62538343c24d4f36bd6876d0c9c21b47/log.full.txt.gz#_2018-08-17_03_46_19_618000

Flake: Unable to communicate with the remote host.

---

ansible/roles/zuul/files/layout.yaml

adding new branch contrail_dpdk_18_05_1 to windows layout

adding new branch contrail_dpdk_18_05_1 to windows layout

---

CIScripts/Checkout/Tentacle.ps1

We removed PSCX so we have to change the usage.

Use expand-archive from powershell instead of pscx

---

Test/TestConfigurationUtils.ps1
Test/Tests/Network/SingleHostWithUtils.Tests.ps1

Added CNM-Plugin configuration file generation
for SingleHostWithUtils test.

Fixed SingleHostWithUtils test

---

Test/Tests/Network/SingleHostWithUtils.Tests.ps1

Because we have an awesome wrapper for `ping` in `Test-Ping`

Use Test-Ping instead of raw ping

---

ansible/roles/zuul/tasks/main.yml

Don't upgrade Zuul nodes on every playbook call.

---

ansible/roles/zuul/files/layout.yaml

add windows ci config for  contrail-deployers-containers

add windows ci config for  contrail-deployers-containers

---

Test/PesterHelpers/PesterHelpers.Tests.ps1
Test/PesterLogger/Get-CurrentPesterScope.Tests.ps1
Test/PesterLogger/PesterLogger.Tests.ps1
Test/PesterLogger/RemoteLogCollector.Tests.ps1
Test/RetryTests.Tests.ps1
Test/TestConfigurationUtils.Tests.ps1
Test/Tests/Component/AgentRestart.Tests.ps1
Test/Tests/Component/CnmPlugin.Tests.ps1
Test/Tests/Component/NodeManager.Tests.ps1
Test/Tests/Component/VTestScenarios.Tests.ps1
Test/Tests/Network/DNS.Tests.ps1
Test/Tests/Network/FloatingIP.Tests.ps1
Test/Tests/Network/SingleHostWithUtils.Tests.ps1
Test/Tests/Network/TunnellingWithAgent.Tests.ps1
Test/Utils/ContrailAPI/DNSServerRepo_Impl.Tests.ps1
Test/Utils/ContrailAPI/IPAMRepo_Impl.Tests.ps1
Test/Utils/DockerImageBuild.Tests.ps1
Test/Utils/NetAdapterInfo/NetAdapter.Tests.ps1
Test/Utils/WinContainers/NewContainer.Tests.ps1
Test/Utils/WinContainers/RemoveAllContainers.Tests.ps1

This reverts commit 6a3698959c0665a24a0dd703aefc28277e753bfb.

Revert "[HOTFIX] disable tests (#405)"

---

CIScripts/Testenv/Testenv.ps1
Test/Tests/Network/FloatingIP.Tests.ps1
Test/Tests/Network/SingleHostWithUtils.Tests.ps1
Test/Utils/ComputeNode/Configuration.ps1
Test/Utils/ComputeNode/Initialize.ps1
Test/Utils/ContrailAPI/DNSServerRepo_Impl.Tests.ps1
Test/Utils/ContrailAPI/IPAMRepo_Impl.Tests.ps1
Test/Utils/ContrailAPI/SecurityGroup.ps1
Test/Utils/ContrailAPI/VirtualNetwork.ps1
Test/Utils/ContrailNetworkManager.ps1
Test/Utils/ContrailNetworkManagerImpl.ps1
Test/Utils/MultiNode/ContrailMultiNodeProvisioning.ps1

In TestenvConfFile in Controller section you can specify,
'AuthMethod: noauth'.

Added option to run test without keystone auth

---

jenkinsfiles/Jenkinsfile.winci-server2016-cad

[Partial-Bug] Jenkinsfile.winci-server2016-cad

---

Test/Tests/Network/SingleHostWithUtils.Tests.ps1

This change just surrounded Describe with Test-WithRetries 3 block.

 Retry 'single compute node' test

---

Jenkinsfile

Recheck flakes on fail only

---

Jenkinsfile
Test/PesterHelpers/PesterHelpers.ps1

Update of used testbed template

---

Test/TestConfigurationUtils.ps1
Test/Utils/ComputeNode/Configuration.ps1
Test/Utils/ComputeNode/Initialize.ps1
Test/Utils/ComputeNode/Installation.ps1
Test/Utils/ComputeNode/Service.ps1
Test/Utils/MultiNode/ContrailMultiNodeProvisioning.ps1
Test/Utils/Testenv/Testbed.Impl.ps1
Test/Utils/Testenv/Testenv.Impl.ps1

All functions used during initialization are transactional.
Improved initialization logging.

Improve test initialization

---

Test/Utils/WinContainers/Containers.ps1

Invoke-NativeCommand sometimes writes exception on error stream,
although it succeeds. That's why we should use Invoke-Command
when possible.

Using Invoke-Command for running docker containers

---

Test/Tests/Network/TunnellingWithAgent.Tests.ps1

Removing reviewers temporarily until CI passes

run vxlan test

---

CIScripts/Build/BuildFunctions.ps1

Needed for: https://review.opencontrail.org/#/c/49677/

Add new env vars that'll be used by scons soon

---

CIScripts/Build.ps1
CIScripts/Build/BuildFunctions.ps1
CIScripts/Deploy/Deployment.ps1
Jenkinsfile
Test/Utils/ComputeNode/Installation.ps1

vRouter is no longer signed with codilime cert, but with one that is
generated by Visual Studio and exported to vRouter.cer file.

Vrouter certificate is now imported in test phase

---

ansible/roles/builder/tasks/main.yml

This removes the agent and tests linking warnings

Switched to newer/better openssl

---

CIScripts/Build.ps1
CIScripts/Build/BuildFunctions.ps1
Jenkinsfile

Reverts Juniper/contrail-windows-ci#572

Revert "Switched to fetch_packages in CI"

---

CIScripts/Build.ps1
CIScripts/Build/BuildFunctions.ps1
Jenkinsfile

Reverts Juniper/contrail-windows-ci#576

Revert "Use fetch_packages in CI"
