ansible/roles/testbed/tasks/main.yml
The goal is for testbeds not to have network connection, so we should do it in template.
=> Pull microsoft docker images in testbed template

CIScripts/Test/Tests/Protocol/SingleHostWithUtils.Tests.ps1
Flags for nh.exe have changed so the tests are broken on master.
Disable utils-based tests so we can enable building Extension in CI.
After enabling Extension, they will be fixed and reenabled.
=> Disable utils-based tests

CIScripts/Build/BuildFunctions.ps1, CIScripts/Common/VMUtils.ps1, CIScripts/Test/Tests/_Old_Tests/ComputeControllerIntegrationTests.ps1, CIScripts/Test/Tests/_Old_Tests/SNATTest.ps1, CIScripts/Test/Utils/ContrailUtils.ps1, CIScripts/Test/Utils/RegisterDefaultResorces.ps1, StaticAnalysis/PSScriptAnalyzerSettings.psd1
Ecxlude this rule due to bug with 0SCreds variable in testenv (SuppressMessage doesn't work)
=> Exclude PSAvoidUsingPlainTextForPassword rule from PSScriptAnalyzer

ansible/vmware-deploy-testenv.yml
This should stop pipeline from proceeding if only some hosts
in testenv fail to deploy.
=> Add any_errors_fatal to multihost plays

CIScripts/Common/VMUtils.ps1
Currently, the VM is specified by address field. This address is passed as a -ComputerName to New-PSSession.
This PR adds a possibility to connect to local Hyper-V VM, by specifying vmName instead of address.
The goal of this PR is to make it easier to use `testenv-conf.yaml`for testing locally.
=> Allow connecting to a local VM in testenv

CIScripts/Build/BuildFunctions.ps1, CIScripts/Common/Invoke-NativeCommand.Tests.ps1, CIScripts/Common/Invoke-NativeCommand.ps1
We have this nice wrapper for executing commands locally, but nothing similar for remote commands. This is something I wished it existed a few times recently.
This PR extends the `Invoke-NativeCommand` to running in `Session`, also cleans up the parameters and makes return value a nice dictionary. This PR also adds tests for this function, which can serve as examples.
=> Add optional -Session parameter to Invoke-NativeCommand

CIScripts/Common/Invoke-NativeCommand.Tests.ps1, CIScripts/Common/Invoke-NativeCommand.ps1
Don't suppress stdout and stderr in Invoke-NativeCommand in case of -CaptureOutput flag and non-zero exitcode of command
=> Don't suppress stdout and stderr in Invoke-NativeCommand

CIScripts/Common/Invoke-UntilSucceeds.Tests.ps1, CIScripts/Common/Invoke-UntilSucceeds.ps1, CIScripts/Test/TestConfigurationUtils.ps1
This PR enables retrying on "Waiting for IP on interface time out"<sup>†</sup> error. Also, we do now print the cause of retry when retrying.
The reason for this error is probably some HNS flakiness. It should be fixed directly in Docker Driver, along with the "HNS unspecified" error. But since we're retrying in CI anyway, I see no reason why we shouldn't retry also on this error.
The actual change is in second commit – https://github.com/Juniper/contrail-windows-ci/commit/35d2e0d4f498229667973b50d21083b1860cef8d. The rest are minor bugfixes and cleanup.
† The _time out_ is a little bit misleading here. Since we no longer have a DHCP and have manual configuration, the correct IP will never appear, no matter how long we wait. When the error occurs, the assigned IP is autoconfiguration one, …
=> Retry starting docker driver also on invalid IP

CIScripts/Test/PesterLogger/RemoteLogCollector.Tests.ps1, CIScripts/Test/RemoveAllContainers.Tests.ps1, CIScripts/Test/Tests/Protocol/TunnellingWithAgent.Tests.ps1
Fixes merge bug between https://github.com/Juniper/contrail-windows-ci/pull/90 and https://github.com/Juniper/contrail-windows-ci/pull/101
```
CommandNotFoundException: The term 'J:\Jenkins\workspace\WinContrail\contrail-docker-driver-gh-devel\CIScripts\Test\Tests\Protocol\..\..\..\Common\VMUtils.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
=> Fix merge bug between Remove-AllContainers and VMUtils.ps1 split.

ansible/group_vars/all/vars
- Removed default templates, because every jenkinsfile/playbook already provides it.
- Use input variables (from prompt) in `testenv_block`.
=> fix: remove default templates from vars

ansible/roles/vmware-template/tasks/create.yml, ansible/roles/vmware-template/tasks/deploy.yml, ansible/roles/vmware-template/tasks/shutdown.yml, ansible/roles/vmware-template/tasks/snapshot.yml
Required by changes in `group_vars/all/vault`
- `datacenter_name` is now `vcenter_datacenter`
- `cluster_name` is now `vcenter_cluster`
- `validate_certs` is now `vcenter_validate_certs`
=> fix: Change datacenter/cluster/validate_certs variable names

Jenkinsfile
AGENT_BUILD_THREADS can be moved to jenkinsfile, since we are using the
same configuration for development and production pipelines.
=> Move AGENT_BUILD_THREADS env to jenkinsfile

CIScripts/Build/BuildFunctions.ps1, Jenkinsfile
During a build we use boost which is already installed on builder
MSBUILD variable is already set on builders
=> Removed symlinking boost and MSBUILD variable

ansible/roles/controller/defaults/main.yml
Update is required because 'centos-openstack-release-ocata' package is not needed
=> Updated contrail-ansible-deployer

CIScripts/Test/Tests/Integration/DockerDriver.Tests.ps1
Reasoning: 
1. we want to use report generator anyways
2. logs are cluttered
Old: http://logs.opencontrail.org/winci/github/WinContrail/contrail-win-ci-gh/1514/detailed_logs/Docker%20Driver.Tests%20for%20module%20agent.Tests%20are%20invoked.log
New: http://logs.opencontrail.org/winci/github/WinContrail/contrail-win-ci-gh/1535/detailed_logs/Docker%20Driver.Tests%20for%20module%20agent.Tests%20are%20invoked.log
=> Use ginkgo succinct flag to make test output very minimal.

ansible/python-requirements.txt
`pkg-resources==0.0.0` was generated by `pip freeze` because of bug in `pip` package definition on Ubuntu (https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463).
=> Remove pkg-resources from requirements.txt

ansible/roles/zuul/files/layout.yaml, ansible/update-zuul-layout.py
Adding openshift-ansible repo to layout.
Project names will now be sorted alphabetically because otherwise the diff is unreadable.
Relevant: https://github.com/Juniper/contrail-windows-ci/pull/157
=> Add openshift-ansible repo. Sort project names automatically.

ansible/roles/zuul/files/layout.yaml, ansible/update-zuul-layout.py
As per @vmahuli's request. We need to be able to handle tungstenfabric organization on gerrit.
=> Handle tungstenfabric and Juniper organizations on gerrit.

CIScripts/Test/TestConfigurationUtils.ps1
Should help debugging `pipe/Contrail` and `Docker Driver was not enabled` flakes.
Possible fix for `Docker Driver was not enabled` – `Element not found` (?)
=> Add docker driver and agent sanity checks

CIScripts/DockerFiles/python-http/Dockerfile
For some reason, default RUN behaves as if the `/U` parameter
was passed to cmd, which resulted in UTF-16 encoded files.
We pass the `/A` (ansi) flag explicitely.
=> Fix encoding of index.html in python Dockerfile

CIScripts/DockerFiles/python-http/Dockerfile
Adds description of change introduced in https://github.com/Juniper/contrail-windows-ci/pull/167
=> Comment on ANSI encoding in Python dockerfile.

Jenkinsfile
Fixes bug, where post stage would fail when before publishing logs:
e.g. here:
https://review.opencontrail.org/#/c/43493/
http://logs.opencontrail.org/winci/0e0e791838484d79bbc9208c55bd7ef1/
This is because robocopy would not copy anything (so robocopy exit code = 0) - but we would throw (because we only care about exit code = 1).
For now, this is a temporary fix using fileExists, because Arkadiusz is refactoring the stashes in that stage atm. 
http://10.84.12.26:8080/job/WinContrail/view/PrivateJobs/job/winci-server2016-devel-gerrit-check/2/console
=> Ensure robocopy is only ran when there is something to copy.

CIScripts/Test/TestConfigurationUtils.ps1, CIScripts/Testenv/Testbed.ps1
We'd like to capture information about panics and crashes
in the Docker Driver. It seems to be easier to do it by
just capturing the whole stderr outside the Docker Driver
rather than manually setting up hooks in the logging library.
=> [WIP] Stop trusting Docker Driver on logging to a file

CIScripts/Checkout.ps1, CIScripts/Common/Invoke-CommandInLocation.Tests.ps1, CIScripts/Test/PesterLogger/Get-CurrentPesterScope.Tests.ps1, CIScripts/Test/PesterLogger/PesterLogger.Tests.ps1, CIScripts/Test/Tests/Integration/AgentRegistering.Tests.ps1, CIScripts/Test/Tests/Integration/DockerDriverNetworking.Tests.ps1, CIScripts/Test/Tests/Integration/Flows.Tests.ps1, CIScripts/Test/Tests/Integration/ForwardingExtension.Tests.ps1, CIScripts/Test/Tests/Integration/Pkt0.Tests.ps1, CIScripts/Test/Tests/Integration/SNAT.Tests.ps1, CIScripts/Test/Tests/Protocol/TunnelingWithUtils.Tests.ps1, CIScripts/Test/Tests/Protocol/WindowsLinuxInterop.Tests.ps1, CIScripts/Test/Tests/Reliability/ForwardingExtLongLeak.Tests.ps1, CIScripts/Test/Utils/RegisterDefaultResorces.ps1, CIScripts/Testenv/Testenv.Tests.ps1, Invoke-Selfcheck.ps1, StaticAnalysis/Invoke-StaticAnalysisTools.ps1
To enable strict mode, we've usually been using `Init.ps1` (which enables strict mode and sets error action). This PR adds this import in all root scripts and tests.
The exception is the `StaticAnalysis/Invoke-StaticAnalysisTools.ps1`—I've decided to set the strict mode explicitely, to keep it independent of `CIScripts`.
I thought that we were already using strict mode everywhere, but adding a warning for missing strict mode in [**shelly**](https://github.com/krdln/shelly) had proved me wrong.
=> Enable strict mode everywhere

ansible/python-requirements.txt
GitHub reported that currently frozen paramiko version is vulnerable to
https://nvd.nist.gov/vuln/detail/CVE-2018-7750
This PR bumps paramiko to first major version which is not vulnerable
=> Bump paramiko version to 2.3.2 due to CVE

CIScripts/Test/PesterLogger/PesterLogger.Tests.ps1, CIScripts/Test/PesterLogger/PesterLogger.ps1, shelly.toml
Makes [shelly](https://github.com/krdln/shelly) warn a little bit less.
=> Add some allow annotations for shelly analyzer

CIScripts/Report/GenerateTestReport.ps1
To make our logs more readable
=> Silence the output of ReportUnit.exe

Test/Utils/CommonTestCode.ps1
This early throw lets us detect this bug early instead of random places later in tests.
=> Throw when container gets an autoconfiguration IP

ansible/roles/testbed/tasks/main.yml
Template: `Template-testbed-201808130708`
[Jenkins job](http://10.84.12.26:8080/job/WinContrail-infra/job/templates/job/create-testbed-template/64/console)
=> Disable docker's nat network in testbed template

CIScripts/BuildStage.ps1
As you can see [here](http://10.84.12.26:8080/job/WinContrail/job/ci-contrail-windows-nightly-debug/configure) I specify `UPLOAD_ARTIFACTS=1`, but since [this job](http://10.84.12.26:8080/job/WinContrail/job/winci-server2016-prod) doesn't have this field, it's not passed there. For proof check [the Jenkins logs](http://10.84.12.26:8080/log/all):
```
Skipped parameter `UPLOAD_ARTIFACTS` as it is undefined on `WinContrail/winci-server2016-prod`.
```
Because of that reason I have to add the field `UPLOAD_ARTIFACTS` to winci-server2016-prod with default set to `0` and then set it to `1` in nightly.
=> Handle UPLOAD_ARTIFACTS in CI

ansible/roles/builder/tasks/main.yml
This is because upgraded docker driver dependencies (hcsshim and
go-winio) rely on type aliasing mechanism, introduced in 1.9.0. But we
might as well skip to 1.10.0.
=> Bump golang to 1.10.0.

Jenkinsfile, utility/split-log-into-stages.sh
This should add a prefix to split log file that we suspect contains the error, based on Jenkins output when a stage is failed. This should make it easier to look for errors in logs.
=> Add simple heuristic for fault detection.

SELFCHECK.md, StaticAnalysis/Invoke-StaticAnalysisTools.ps1, StaticAnalysis/README.md, ansible/roles/builder/tasks/main.yml
We need at least 1.17 because they fixed a bug with importing classes.
Template creation succeeds: http://10.84.12.26:8080/job/WinContrail-infra/job/templates/job/create-builder-template/120/
=> Add min version requirement for PSScriptAnalyzer.

CIScripts/Testenv/Testenv.ps1, Test/TestConfigurationUtils.ps1, Test/Tests/testenv-conf.yaml.sample, ansible/roles/testenv-save-conf/templates/testenv-conf.yaml.j2
Docker driver now requires to specify the method of authentication.
Supported auth methods: keystone|noauth.
=> Add flag to starting docker-driver service

Jenkinsfile, StaticAnalysis/Invoke-StaticAnalysisTools.ps1
We used to install PSScriptAnalyzer using PSget. So we checked its
version using Get-Package. But now it's installed by chocolatey, so it
doesn't appear in Get-Package. Instead, we need to check Get-Module.
=>  Allow PSScriptAnalyzer installed by choco in Invoke script.

ansible/builders.yml, ansible/roles/builder/tasks/main.yml, ansible/roles/testbed/tasks/main.yml
- Removed PSCX installation since Ansible _promises_ that `.zip` archives are supported natively:
- https://docs.ansible.com/ansible/2.4/win_unzip_module.html#synopsis
- Add Docker installation to builder role. Used in nightly builds.
- Add playbook for updating builders.
TO DO:
=> builder: Docker installation

ansible/roles/contrail-ansible-deployer/templates/instances.j2
Added Java options to limit a maximum allocation pool to 2 GB, to avoid _hungry Cassandra_ syndrome.
=> c-a-d: Limit Java memory usage

Jenkinsfile
Since PSScriptAnalyser is already deployed on builder nodes, `builder-choco-analyzer` label can removed.
=> jenkins: Use builder label in Static analysis

Test/Tests/Network/FloatingIP.Tests.ps1, Test/Tests/Network/TunnellingWithAgent.Tests.ps1, Test/Utils/Network/Connectivity.ps1, Test/Utils/Network/UDPClient.ps1, Test/Utils/Network/UDPEchoServer.ps1
Test suite files were getting too cluttered and there was some duplication with Test-Ping.
(Not only it is used between two files, but also move tests that would use it are coming soon - DNS).
=> Move Test- methods to separate directory.

Test/PesterLogger/RemoteLogCollector.Tests.ps1, Test/PesterLogger/RemoteLogCollector.ps1, Test/TestConfigurationUtils.ps1, Test/Tests/Network/TunnellingWithAgent.Tests.ps1
This will better reflect normal user environment and hopefully reduce
random tests' failures.
=> Initialize compute nodes once in TunnellingWithAgent tests

CIScripts/Testenv/Testbed.ps1, Jenkinsfile
If connection breaks during publishing monitoring scripts whole job
fails even if tests pass - retries will solve part of this problem.
Sensible retries to session connection are added as well.
=> Add retries to session connection and publishing monitoring scripts.

Test/TestConfigurationUtils.ps1
Because I do not know the way to reproduce this bug, we need to add debug output to verify what process locks agent's REST API port.
=> Debug output for Agent's REST API port getting locked

Test/TestConfigurationUtils.ps1, Test/Utils/ComputeNode/Configuration.ps1
Additional fixes:
- CNM-Plugin stdout and stderr goes to contrail-cnm-plugin-std.log
- default CNM-Plugin configuration filename is contrail-cnm-plugin.conf
=> Removed remaining CNM-Plugin cmdline arguments

Test/PesterLogger/PesterLogger.ps1, Test/TestConfigurationUtils.ps1, Test/Utils/ComputeNode/Configuration.ps1, Test/Utils/ComputeNode/Initialize.ps1, Test/Utils/NetAdapterInfo/RemoteHost.ps1, Test/Utils/NetAdapterInfo/RemoteVM.ps1
Reverts some annotations introduced in #334
=> Remove `allow unused-imports` for shelly is fixed

Test/TestConfigurationUtils.ps1, Test/Utils/ComputeNode/Configuration.ps1
Right now, agent's msi creates directory which holds configuration files and with [this](https://review.opencontrail.org/#/c/47189/) it will no more, so let's create the directory in CI.
=> Check if default configuration folder exists

ansible/python-requirements.txt, monitoring/requirements.txt, monitoring/requirements_windows.txt
GitHub scanner reported the following issues:
- `paramiko>=2.3.3` - https://nvd.nist.gov/vuln/detail/CVE-2018-1000805;
- `pyopenssl>=17.5.0` - https://nvd.nist.gov/vuln/detail/CVE-2018-1000807,
https://nvd.nist.gov/vuln/detail/CVE-2018-1000808;
- `ansible>=2.4.5` - https://nvd.nist.gov/vuln/detail/CVE-2018-10855;
- `requests>=2.20.0` - https://nvd.nist.gov/vuln/detail/CVE-2018-18074;
=> Bump Python requirements due to CVEs

Test/Utils/Network/UDPClient.ps1
Sometimes docker hangs and because `docker exec` is blocking operation, job is aborted because of timeout.
=> Add timeout for udp polling

CIScripts/Test.ps1
Without exit 0 at the end of script jenkins will fail if something
has been written in error stream. Exceptions will still cause job
to fail, because they will prevent exit 0 from being executed.
=> Test script run in jenkins exit 0 when tests pass

CIScripts/Build/Containers.ps1, CIScripts/Build/Dockerfile
For Windows Server 2019 we will need to use other base images for
containers, that's why we need to parametrize Dockerfile.
Also on WS 2019, nanoserver doesn't have powershell, so we cannot
unpack zip with artifacts.
=> Dockerfile to build containers parametrized

CIScripts/Build/BuildFunctions.ps1
New cmocka is linked dynamically so I need `build/bin` added to path before running kernel tests. This is just a temporal change, as this code is totally refactored in #557
=> Moved running kernel tests to a place with edited path
